exports.seed = function(knex, Promise) {
  return knex('games').insert([
    {igdb_id: 41608 , title: 'Halo: The Master Chief Collection' , cover_url: '//images.igdb.com/igdb/image/upload/t_thumb/kuaub4pjaajuepmlxuq3.jpg' , desc: 'Relive the greatest adventures of the ultimate solder with Halo: The Master Chief Collection, which includes the complete story of the Master Chief on one console for the first time ever. Halo: Combat Evolved , Halo 2, Halo 3 and Halo 4 are all packed into this massive package. And not only is the debut Halo delivered in its acclaimed Anniversary package, but for the first time, an entirely remastered version of the iconic sequel that revolutionized online console gaming is available with the Halo 2 Anniversary version of the game. This collection lets you experience Halo in an all-new way, at higher visual fidelity running at 60 frames per second (fps) on dedicated servers. \n \nHalo: The Master Chief Collection features curated campaign and multiplayer playlists across all four games and features more than 100 multiplayer maps -- authentic to their original release. In addition, Halo 2 Anniversary includes six all-new maps built from the ground up for Xbox One.'},
    {igdb_id: 25076, title: 'Red Dead Redemption 2', cover_url: '//images.igdb.com/igdb/image/upload/t_thumb/yfk9f2lbo0r7slytuhra.jpg' , desc: 'Developed by the creators of Grand Theft Auto V and Red Dead Redemption, Red Dead Redemption 2 is an epic tale of life in America’s unforgiving heartland. The game\'s vast and atmospheric world will also provide the foundation for a brand new online multiplayer experience.' },
    {igdb_id: 231 , title: 'Half-Life' , cover_url: '//images.igdb.com/igdb/image/upload/t_thumb/twbyn9lpdljjxedxudn5.jpg', desc: 'Dr. Gordon Freeman doesn\'t speak, but he\'s got a helluva story to tell. This first-person roller-coaster initiated a new era in the history of action games by combining engrossing gameplay, upgraded graphics, ingenious level design and a revolutionary story that may not be all that it seems, told not through cutscenes, but through the visual environment.'},
    {igdb_id: 233, title: 'Half-Life 2', cover_url: '//images.igdb.com/igdb/image/upload/t_thumb/obcjdcsaq2ndxqi7zqdf.jpg', desc: 'Half-Life 2 (stylized as HλLF-LIFE²), the sequel to Half-Life, is a first-person shooter video game and part of the Half-Life series. Developed by Valve Corporation, it was initially released on November 16, 2004, following a protracted five-year, $40 million development cycle, during which a substantial part of the project was leaked and distributed on the Internet.'},
    {igdb_id: 7346, title: 'The Legend of Zelda: Breath of the Wild', cover_url: '//images.igdb.com/igdb/image/upload/t_thumb/mievpzb9rbzzenmznvnr.jpg', desc: 'Step into a world of discovery, exploration and adventure in The Legend of Zelda: Breath of the Wild, a boundary-breaking new game in the acclaimed series. Travel across fields, through forests and to mountain peaks as you discover what has become of the ruined kingdom of Hyrule in this stunning open-air adventure.'},
    {igdb_id: 72870, title: 'Horizon: Zero Dawn Complete Edition', cover_url: '//images.igdb.com/igdb/image/upload/t_thumb/co1ht2.jpg', desc: 'In an era where machines roam the land and mankind is no longer the dominant species, a young hunter named Aloy embarks on a journey to discover her destiny. Explore a vibrant and lush world inhabited by mysterious mechanized creatures. Embark on a compelling, emotional journey and unravel mysteries of tribal societies, ancient artefacts and enhanced technologies that will determine the fate of this planet and of life itself. \n \nHorizon: Zero Dawn Complete Edition includes Horizon Zero Dawn and the frozen wilds expansion.'}    
  ])
  // .then(() =>{
  //   return knex.raw(`SELECT setval('games_id_seq', (SELECT max(id) FROM games));`)})
};
